import os
import glob
import time
import shutil
import re
import subprocess
from pathlib import Path

import sys

# Paths
HOST_BASE_DIR = Path(__file__).resolve().parent
TEMP_DIR = HOST_BASE_DIR / "temp_frontend_dir"
HISTORY_DIR = HOST_BASE_DIR / "frontend_history"

# Settings
SPECTRUM_TYPE = "delay"
SPEC_MIN = -143.9031990144428
SPEC_MAX = -23.31242051071544
MODEL_PATH = "output/rf_model_delay_3.5ghz"
ITERATION = 40000

# Initialize directories
os.makedirs(TEMP_DIR, exist_ok=True)
os.makedirs(HISTORY_DIR, exist_ok=True)

def clear_temp_dir():
    for f in TEMP_DIR.glob("*.png"):
        f.unlink()

def generate_step(x, y, z):
    """
    Executes Sionna simulation inside Docker to generate ground truth spectrum.
    Returns path to the generated image in the history folder.
    """
    clear_temp_dir()
    
    # We use a temp directory that maps inside Docker (assuming /tf/Project_1 maps to Project_1)
    # The output-dir path must be relative to the docker workspace or absolute.
    # To be safe, we'll use "temp_frontend_dir" which will be in /tf/Project_1/temp_frontend_dir
    docker_cmd = [
        "docker", "exec", "-w", "/tf/Project_1", "magical_margulis", 
        "python3", "generate_csi_dataset.py",
        "--rx-pos", str(x), str(y), str(z),
        "--spectrum-type", SPECTRUM_TYPE,
        "--spec-min", str(SPEC_MIN),
        "--spec-max", str(SPEC_MAX),
        "--output-dir", "temp_frontend_dir"
    ]
    
    # Run the docker command
    result = subprocess.run(docker_cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Error generating spectrum: {result.stderr}")
    
    # Find the generated PNG image
    generated_files = list(TEMP_DIR.glob("*.png"))
    if not generated_files:
        raise FileNotFoundError("No PNG file was generated by Sionna simulation.")
        
    img_path = generated_files[0]
    
    # Move to history dir with timestamp
    timestamp = int(time.time() * 1000)
    history_img_name = f"step_{timestamp}_{img_path.name}"
    history_img_path = HISTORY_DIR / history_img_name
    shutil.move(str(img_path), str(history_img_path))
    
    return str(history_img_path)

def predict_step(img_path, last_x=None, last_y=None, last_z=None, last_yaw=None):
    """
    Runs gradient_descent_localization.py for the given target image.
    Parses and returns the estimated X, Y, Z, Yaw and error.
    """
    # Working directory is the RF-3DGS folder
    rf_3dgs_dir = HOST_BASE_DIR / "RF-3DGS"
    
    # Ensure we use the rf-3dgs conda environment's python which has torch/cuda modules installed
    conda_python = "/home/ved/anaconda3/envs/rf-3dgs/bin/python"
    
    cmd = [
        conda_python, "gradient_descent_localization.py",
        "--target_image", os.path.abspath(img_path),
        "--model_path", MODEL_PATH,
        "--iteration", str(ITERATION)
    ]
    
    if last_x is not None and last_y is not None and last_z is not None:
        cmd.extend([
            "--coarse_x", str(last_x),
            "--coarse_y", str(last_y),
            "--coarse_z", str(last_z)
        ])
        if last_yaw is not None:
            cmd.extend(["--coarse_yaw", str(last_yaw)])
    
    start_time = time.time()
    result = subprocess.run(cmd, cwd=str(rf_3dgs_dir), capture_output=True, text=True)
    elapsed = time.time() - start_time
    
    if result.returncode != 0:
        # gradient_descent_localization could still fail, let's print stderr if completely failed
        pass
        
    output = result.stdout + "\n" + result.stderr
    
    import re
    
    est_x, est_y, est_z, yaw, error = None, None, None, None, None
    
    # Extract Optimized Position using regex on the bottom portion of output
    # First split by line to process reliably
    for line in output.split('\n'):
        # Matches: "  X: 0.388004 m"
        x_match = re.search(r'X:\s*([-\d.]+)\s*m', line)
        if x_match:
            try: est_x = float(x_match.group(1))
            except: pass
            
        y_match = re.search(r'Y:\s*([-\d.]+)\s*m', line)
        if y_match:
            try: est_y = float(y_match.group(1))
            except: pass
            
        z_match = re.search(r'Z:\s*([-\d.]+)\s*m', line)
        if z_match:
            try: est_z = float(z_match.group(1))
            except: pass
            
        yaw_match = re.search(r'Optimized Yaw:\s*([-\d.]+)', line)
        if yaw_match:
            try: yaw = float(yaw_match.group(1))
            except: pass
            
        err_match = re.search(r'Distance from Real Position.*:\s*([-\d.]+)', line)
        if err_match:
            try: error = float(err_match.group(1))
            except: pass

    return {
        "est_x": est_x,
        "est_y": est_y,
        "est_z": est_z,
        "est_yaw": yaw if yaw is not None else 0.0,
        "error": error,
        "time_s": elapsed,
        "log": getattr(result, 'stdout', ''),
    }

def step_simulation(x, y, z, last_x=None, last_y=None, last_z=None, last_yaw=None):
    """
    Convenience method: Generates the true spectrum and predicts the pose.
    """
    img_path = generate_step(x, y, z)
    result = predict_step(img_path, last_x, last_y, last_z, last_yaw)
    result["gt_x"] = x
    result["gt_y"] = y
    result["gt_z"] = z
    result["img"] = img_path
    return result

if __name__ == "__main__":
    print("Testing runner...")
    res = step_simulation(0.5, 0.5, 2.0)
    print(res)
